schemeName = "helloworld"
buildPath = "fastlane/build/"
buildName = "hello_world"

before_all do



end

lane :release do

    update_version_number()

    install_pods()

    unit_test()

    build_project()

    distribute_to_testflight()

end

# Update version number
lane :update_version_number do
    version_number_at_testflight = latest_testflight_build_number(
        username: "shafayat@bs-23.net",
        team_id: "390381",
        app_identifier: "com.shafayat.helloworld"
    )
    puts version_number_at_testflight
    increment_build_number(build_number: version_number_at_testflight + 1)

end
# Pod install
lane :install_pods do

    cocoapods(
        clean_install: false,
        use_bundle_exec: true
    )

end

# Unit test
lane :unit_test do

    scan(
        workspace: "helloworld.xcworkspace",
        device: "iPhone 12",
        scheme: schemeName
    )

end

# Build project
lane :build_project do

    gym(
        build_path: "fastlane/build/",
        clean: true,
        export_method: "app-store",
        export_options: {
            provisioningProfile: {
                "com.shafayat.helloworld": "match AppStore com.shafayat.helloworld"
            }
        },
        include_symbols: true,
        output_directory: "fastlane/build/",
        output_name: buildName,
        scheme: schemeName,
        silent: false,
        workspace: "helloworld.xcworkspace"
    )

end

# Upload to test flight
# App specific password trun-bmxl-xatl-ruqn
lane :distribute_to_testflight do

    upload_to_testflight(
        app_identifier: "com.shafayat.helloworld",
        ipa: buildPath + buildName + ".ipa",
        username: ENV['APPLE_USERNAME'],
        skip_waiting_for_build_processing: true,
        skip_submission: true, # Must for app specific password
        apple_id: "1602325618"  # Must for app specific password
    )

end

lane :push_to_remote do

    git_add(path: "*")
    git_commit(
        path: "*",
        message: "Release to testflight with updating version number"
    )
    push_to_git_remote(
        remote: "origin"
    )

end

after_all do

    # Push updates to git repo
    # push_to_git_remote()
    
end